Update botssh

diff --git a/Modulos/botssh b/Modulos/botssh
--- a/Modulos/botssh
+++ b/Modulos/botssh
@@ -33,21 +33,25 @@ fun_botOnOff () {
           echo -e "\E[44;1;37m             BOT YASH-SSH INSTALLER                \E[0m\n"
           echo -ne "\033[1;32mINFORM YOUR TOKEN:\033[1;37m "; read tokenbot
   	    echo ""
+  	    echo -ne "\033[1;32mINFORM YOUR ID:\033[1;37m "; read iduser
           clear
           echo -e "\033[1;32mSTARTING YASH-SSH BOT \033[0m\n"
           fun_bot1 () {
   	        [[ ! -e "/etc/SSHPlus/ShellBot.sh" ]] && wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/master/ShellBot.sh > /etc/SSHPlus/ShellBot.sh
   	        cd /etc/SSHPlus
-  	        screen -dmS bot_plus ./bot $tokenbot > /dev/null 2>&1
+  	        screen -dmS bot_plus ./bot $tokenbot $iduser > /dev/null 2>&1
               [[ $(grep -wc "bot_plus" /etc/autostart) = '0' ]] && {
-		          echo -e "ps x | grep 'bot_plus' | grep -v 'grep' && echo 'ON' || cd /etc/SSHPlus && sudo screen -dmS bot_plus ./bot $tokenbot && cd $HOME" >> /etc/autostart
+		          echo -e "ps x | grep 'bot_plus' | grep -v 'grep' && echo 'ON' || cd /etc/SSHPlus && sudo screen -dmS bot_plus ./bot $tokenbot $iduser && cd $HOME" >> /etc/autostart
 		      } || {
 		          sed -i '/bot_plus/d' /etc/autostart
-		          echo -e "ps x | grep 'bot_plus' | grep -v 'grep' && echo 'ON' || cd /etc/SSHPlus && sudo screen -dmS bot_plus ./bot $tokenbot && cd $HOME" >> /etc/autostart
+		          echo -e "ps x | grep 'bot_plus' | grep -v 'grep' && echo 'ON' || cd /etc/SSHPlus && sudo screen -dmS bot_plus ./bot $tokenbot $iduser && cd $HOME" >> /etc/autostart
 		      }
 		      [[ $(crontab -l|grep -c "verifbot") = '0' ]] && (crontab -l 2>/dev/null; echo "@daily /bin/verifbot") | crontab -
   	        cd $HOME
           }
+          fun_bar 'fun_bot1'
+          [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m YASH-SSH BOT ON !\033[0m" || echo -e "\n\033[1;31m ERROR! RE-ANALYZE YOUR INFORMATION\033[0m"
+          sleep 3
           menu
       } || {
           clear
@@ -58,7 +62,7 @@ fun_botOnOff () {
               [[ $(grep -wc "bot_plus" /etc/autostart) != '0' ]] && {
 		          sed -i '/bot_plus/d' /etc/autostart
 		      }
-		      [[ $(crontab -l|grep -c "verifbot") != '0' ]] && crontab -l | grep -v 'verifbot' | crontab -
+		      [[ $(crontab -l|grep -c "verifybot") != '0' ]] && crontab -l | grep -v 'verifbot' | crontab -
               sleep 1
           }
           fun_bar 'fun_bot2'
@@ -69,13 +73,14 @@ fun_botOnOff () {
 }
 
 fun_instbot () {
-echo -e "\E[44;1;37m             BOT SSHPLUS INSTALLER                \E[0m\n"
+echo -e "\E[44;1;37m             BOT YASH-SSH INSTALLER                \E[0m\n"
 echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATTENTION \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
 echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mBY YOUR TELEGRAM ACCESS THE FOLLOWING BOT\033[1;37m:\033[0m"
 echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREATE YOUR BOT \033[1;31mOPTION: \033[1;37m/newbot\033[0m"
+echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@my_id_bot \033[1;33mAND GET YOUR ID \033[1;31mOPTION: \033[1;37m/id\033[0m"
 echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
 echo ""
-read -p "DESEJA CONTINUAR ? [s/n]: " -e -i n resposta
+read -p "DO YOU WISH TO CONTINUE ? [s/n]: " -e -i n resposta
 if [[ "$resposta" = 's' ]]; then
   	fun_botOnOff
   else
@@ -85,4 +90,3 @@ if [[ "$resposta" = 's' ]]; then
 fi
 }
 [[ -f "/etc/SSHPlus/ShellBot.sh" ]] && fun_botOnOff || fun_instbot
-#fim
